# Generated by Django 5.1.1 on 2024-12-27 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edict',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proclamation', models.CharField(max_length=200)),
                ('uasg', models.CharField(max_length=200)),
                ('contractor', models.CharField(max_length=200)),
                ('object', models.CharField(blank=True, max_length=2000, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('dispute_model', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True, null=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edict_platform', to='notice.platform')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edict_status', to='notice.status')),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('archive', models.FileField(blank=True, null=True, upload_to='edict/')),
                ('edict', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Archive_edict', to='notice.edict')),
            ],
        ),
    ]
